export default Object.freeze({
  LIBRARY_REGISTERED: 'LIBRARY_REGISTERED', LIBRARY_APPROVED: 'LIBRARY_APPROVED', LIBRARY_REJECTED: 'LIBRARY_REJECTED',
  LIBRARIAN_REGISTERED: 'LIBRARIAN_REGISTERED', LIBRARIAN_APPROVED: 'LIBRARIAN_APPROVED',
  STUDENT_REGISTERED: 'STUDENT_REGISTERED', SEAT_ASSIGNED: 'SEAT_ASSIGNED', SEAT_RELEASED: 'SEAT_RELEASED',
  FEE_PAYMENT_RECORDED: 'FEE_PAYMENT_RECORDED', FEE_OVERDUE: 'FEE_OVERDUE', CONCERN_CREATED: 'CONCERN_CREATED', CONCERN_RESOLVED: 'CONCERN_RESOLVED'
});
